export type Resource = {
  id: number;
  name: string;
  type: string;
  url: string | null;
  platform: string;
  category: string;
  description: string;
  bestFor: string;
  audience: string;
  access: string;
  keywords: string;
};

export const resources: Resource[] = [
  {
    "id": 1,
    "name": "Adobe Background Remover",
    "type": "Tool",
    "url": null,
    "platform": "Adobe Background Remover",
    "category": "AI",
    "description": "Adobe web utility for removing image backgrounds.",
    "bestFor": "Use this resource for adobe web utility for removing image backgrounds.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 2,
    "name": "Aiverse Design",
    "type": "Website",
    "url": null,
    "platform": "Aiverse Design",
    "category": "AI",
    "description": "Library of AI-focused UX and interaction references.",
    "bestFor": "Use this resource for library of AI-focused UX and interaction references.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, website"
  },
  {
    "id": 3,
    "name": "ChatGPT",
    "type": "Website",
    "url": null,
    "platform": "OpenAI",
    "category": "AI",
    "description": "A conversational AI tool used for various text-based tasks.",
    "bestFor": "Generating text and assisting with queries.",
    "audience": "Beginner",
    "access": "Freemium",
    "keywords": "ai, chatbot, openai, productivity"
  },
  {
    "id": 4,
    "name": "Claude Code",
    "type": "Tool",
    "url": null,
    "platform": "Claude Code",
    "category": "AI",
    "description": "AI coding agent referenced for working from design references and codebases.",
    "bestFor": "Use this resource for aI coding agent referenced for working from design references and codebases.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 5,
    "name": "Codex by GPT",
    "type": "Tool",
    "url": null,
    "platform": "OpenAI",
    "category": "AI",
    "description": "An AI tool used for generating and inserting code structures into development projects.",
    "bestFor": "Automating code insertion and customizing component structures via prompts.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "ai coding, gpt, automation, developer tools"
  },
  {
    "id": 6,
    "name": "Film AI",
    "type": "Tool",
    "url": null,
    "platform": "Film AI",
    "category": "AI",
    "description": "AI resource for generating film-style effects and visual scenes.",
    "bestFor": "Use this resource for aI resource for generating film-style effects and visual scenes.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 7,
    "name": "Google ImageFX",
    "type": "Tool",
    "url": null,
    "platform": "Google ImageFX",
    "category": "AI",
    "description": "Google Labs tool for generating images from text prompts.",
    "bestFor": "Use this resource for google Labs tool for generating images from text prompts.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 8,
    "name": "Hailuo AI",
    "type": "Tool",
    "url": null,
    "platform": "Hailuo AI",
    "category": "AI",
    "description": "Generative AI platform for creating images and videos.",
    "bestFor": "Use this resource for generative AI platform for creating images and videos.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 9,
    "name": "Kive AI",
    "type": "Tool",
    "url": null,
    "platform": "Kive AI",
    "category": "AI",
    "description": "AI-powered creative asset organization and visual inspiration platform.",
    "bestFor": "Use this resource for aI-powered creative asset organization and visual inspiration platform.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 10,
    "name": "Kling AI",
    "type": "Tool",
    "url": null,
    "platform": "Kling AI",
    "category": "AI",
    "description": "Generative AI platform focused on AI video creation.",
    "bestFor": "Use this resource for generative AI platform focused on AI video creation.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 11,
    "name": "Let's Enhance",
    "type": "Tool",
    "url": null,
    "platform": "Let's Enhance",
    "category": "AI",
    "description": "AI-powered image enhancement and upscaling service.",
    "bestFor": "Use this resource for aI-powered image enhancement and upscaling service.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 12,
    "name": "MagicPath",
    "type": "Tool",
    "url": null,
    "platform": "MagicPath",
    "category": "AI",
    "description": "AI-assisted product and interface design tool referenced for advanced web-app workflows.",
    "bestFor": "Use this resource for aI-assisted product and interface design tool referenced for advanced web-app workflows.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 13,
    "name": "Magnific AI",
    "type": "Tool",
    "url": null,
    "platform": "Magnific AI",
    "category": "AI",
    "description": "AI image enhancement and upscaling platform.",
    "bestFor": "Use this resource for aI image enhancement and upscaling platform.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 14,
    "name": "Manus AI",
    "type": "Tool",
    "url": null,
    "platform": "Manus",
    "category": "AI",
    "description": "An AI agent platform capable of creating websites, applications, and spreadsheets based on references.",
    "bestFor": "Developing web applications and landing pages by inspecting live URL references or Figma files.",
    "audience": "Developer",
    "access": "Paid",
    "keywords": "ai website builder, ai agent, web development, automation, manus ai"
  },
  {
    "id": 15,
    "name": "Midjourney",
    "type": "Tool",
    "url": null,
    "platform": "Midjourney",
    "category": "AI",
    "description": "Generative AI service for creating stylized images from prompts.",
    "bestFor": "Use this resource for generative AI service for creating stylized images from prompts.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 16,
    "name": "Nano Banana",
    "type": "Tool",
    "url": null,
    "platform": "Nano Banana",
    "category": "AI",
    "description": "Google generative image model referenced for AI image creation and editing.",
    "bestFor": "Use this resource for google generative image model referenced for AI image creation and editing.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 17,
    "name": "PicWish",
    "type": "Tool",
    "url": null,
    "platform": "PicWish",
    "category": "AI",
    "description": "AI image editor and background-removal utility.",
    "bestFor": "Use this resource for aI image editor and background-removal utility.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 18,
    "name": "PixCut",
    "type": "Tool",
    "url": null,
    "platform": "PixCut",
    "category": "AI",
    "description": "AI image utility referenced for background removal and image editing.",
    "bestFor": "Use this resource for aI image utility referenced for background removal and image editing.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 19,
    "name": "Runway",
    "type": "Tool",
    "url": null,
    "platform": "Runway",
    "category": "AI",
    "description": "Generative AI platform for creating and editing images and videos.",
    "bestFor": "Use this resource for generative AI platform for creating and editing images and videos.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 20,
    "name": "The Shape of AI",
    "type": "Website",
    "url": null,
    "platform": "The Shape of AI",
    "category": "AI",
    "description": "Resource exploring AI interaction patterns and product experiences.",
    "bestFor": "Use this resource for resource exploring AI interaction patterns and product experiences.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, website"
  },
  {
    "id": 21,
    "name": "Visual Electric",
    "type": "Tool",
    "url": null,
    "platform": "Visual Electric",
    "category": "AI",
    "description": "AI image-generation workspace designed for creative professionals.",
    "bestFor": "Use this resource for aI image-generation workspace designed for creative professionals.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "ai, design resource, tool"
  },
  {
    "id": 22,
    "name": "Canva",
    "type": "Tool",
    "url": null,
    "platform": "Canva",
    "category": "Branding",
    "description": "Online design platform for creating graphics, presentations, social posts, and visual assets.",
    "bestFor": "Use this resource for online design platform for creating graphics, presentations, social posts, and visual assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "branding, design resource, tool"
  },
  {
    "id": 23,
    "name": "Colormind",
    "type": "Tool",
    "url": "http://colormind.io/",
    "platform": "Colormind",
    "category": "Branding",
    "description": "AI-assisted color palette generator that can learn styles from images and media.",
    "bestFor": "Use this resource for aI-assisted color palette generator that can learn styles from images and media.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "branding, design resource, tool"
  },
  {
    "id": 24,
    "name": "Coolors",
    "type": "Tool",
    "url": null,
    "platform": "Coolors",
    "category": "Branding",
    "description": "A fast color palette generator.",
    "bestFor": "Generating random or custom color schemes quickly.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "color, palette, branding, generator"
  },
  {
    "id": 25,
    "name": "Freepik",
    "type": "Website",
    "url": null,
    "platform": "Freepik",
    "category": "Branding",
    "description": "A platform offering millions of free vector icons, stock photos, and PSD files.",
    "bestFor": "Downloading high-quality graphic assets for projects.",
    "audience": "Designer",
    "access": "Freemium",
    "keywords": "vectors, photos, assets, graphic design"
  },
  {
    "id": 26,
    "name": "Upwork",
    "type": "Website",
    "url": null,
    "platform": "Upwork",
    "category": "Business",
    "description": "The largest platform for finding freelance work.",
    "bestFor": "Finding long-term and high-quality client projects.",
    "audience": "Designer",
    "access": "Account Required",
    "keywords": "freelance, jobs, business, hiring"
  },
  {
    "id": 27,
    "name": "Better Logo Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Better Logo Figma Plugin",
    "category": "Figma",
    "description": "Figma plugin referenced for improving or generating logo assets.",
    "bestFor": "Use this resource for figma plugin referenced for improving or generating logo assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 28,
    "name": "Content Reel",
    "type": "Tool",
    "url": null,
    "platform": "Figma Plugin",
    "category": "Figma",
    "description": "A Figma plugin for populating designs with real content.",
    "bestFor": "Pulling text strings, avatars, and icons into designs.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "figma plugin, content, data, ui design"
  },
  {
    "id": 29,
    "name": "Contrast Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Contrast Figma Plugin",
    "category": "Figma",
    "description": "Checks text and interface color contrast for accessibility.",
    "bestFor": "Use this resource for checks text and interface color contrast for accessibility.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 30,
    "name": "Design Documentation Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Design Documentation Figma Plugin",
    "category": "Figma",
    "description": "Figma resource for producing specifications and design documentation.",
    "bestFor": "Use this resource for figma resource for producing specifications and design documentation.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 31,
    "name": "Feather Icons Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Feather Icons Figma Plugin",
    "category": "Figma",
    "description": "Provides Feather icons directly inside Figma.",
    "bestFor": "Use this resource for provides Feather icons directly inside Figma.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 32,
    "name": "Figma",
    "type": "Tool",
    "url": null,
    "platform": "Figma",
    "category": "Figma",
    "description": "Interface design, prototyping and collaboration tool available as Windows, Mac, and Web apps.",
    "bestFor": "Designing user interfaces and creating prototypes.",
    "audience": "Designer",
    "access": "Freemium",
    "keywords": "design, ui, ux, prototyping, collaboration"
  },
  {
    "id": 33,
    "name": "Figma Community",
    "type": "Website",
    "url": null,
    "platform": "Figma Community",
    "category": "Figma",
    "description": "A repository of community-made assets for Figma.",
    "bestFor": "Finding templates, libraries, and plugins.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "figma, assets, templates, plugins"
  },
  {
    "id": 34,
    "name": "Figma Components",
    "type": "Website",
    "url": null,
    "platform": "Figma Components",
    "category": "Figma",
    "description": "Component collection for creating designs directly in Figma.",
    "bestFor": "Use this resource for component collection for creating designs directly in Figma.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, website"
  },
  {
    "id": 35,
    "name": "Framer Extension for Figma",
    "type": "Tool",
    "url": null,
    "platform": "Framer/Figma Community",
    "category": "Figma",
    "description": "A Chrome extension that allows users to capture a live webpage and paste it into Figma as an editable layout.",
    "bestFor": "Extracting layouts from existing websites to edit or use as base templates in Figma.",
    "audience": "Designer",
    "access": "Freemium",
    "keywords": "figma extension, html to figma, layout capture, web design tool"
  },
  {
    "id": 36,
    "name": "Html to Design Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Framer Skills",
    "category": "Figma",
    "description": "A plugin that converts websites into fully editable Figma designs.",
    "bestFor": "Extracting layouts and converting web pages to design files.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, plugin, html, web design"
  },
  {
    "id": 37,
    "name": "Insert Big Image Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Insert Big Image Figma Plugin",
    "category": "Figma",
    "description": "Adds large images to Figma without losing quality.",
    "bestFor": "Use this resource for adds large images to Figma without losing quality.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 38,
    "name": "LottieFiles for Figma",
    "type": "Tool",
    "url": null,
    "platform": "LottieFiles for Figma",
    "category": "Figma",
    "description": "Imports and works with Lottie animations directly in Figma.",
    "bestFor": "Use this resource for imports and works with Lottie animations directly in Figma.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 39,
    "name": "Mockups Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Mockups Figma Plugin",
    "category": "Figma",
    "description": "Creates and applies mockups directly inside Figma.",
    "bestFor": "Use this resource for creates and applies mockups directly inside Figma.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 40,
    "name": "Noise & Texture Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Noise & Texture Figma Plugin",
    "category": "Figma",
    "description": "Figma plugin for applying noise and texture effects to design elements.",
    "bestFor": "Use this resource for figma plugin for applying noise and texture effects to design elements.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 41,
    "name": "Perspective Toolkit Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Perspective Toolkit Figma Plugin",
    "category": "Figma",
    "description": "Figma plugin for perspective, skew, isometric, and presentation transformations.",
    "bestFor": "Use this resource for figma plugin for perspective, skew, isometric, and presentation transformations.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 42,
    "name": "Pitchdeck Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Pitchdeck Figma Plugin",
    "category": "Figma",
    "description": "Figma resource for designing presentations and interactive PDF-style decks.",
    "bestFor": "Use this resource for figma resource for designing presentations and interactive PDF-style decks.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 43,
    "name": "Real People Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Real People Figma Plugin",
    "category": "Figma",
    "description": "Figma placeholder plugin for adding realistic people and content to interface designs.",
    "bestFor": "Use this resource for figma placeholder plugin for adding realistic people and content to interface designs.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 44,
    "name": "SegmentUI",
    "type": "Template",
    "url": null,
    "platform": "Framer Skills",
    "category": "Figma",
    "description": "UI Kits and components specifically designed for Framer and Figma.",
    "bestFor": "Speeding up the design-to-development workflow.",
    "audience": "Intermediate",
    "access": "Unknown",
    "keywords": "ui kit, framer, figma, components"
  },
  {
    "id": 45,
    "name": "UI Wiki",
    "type": "Website",
    "url": null,
    "platform": "UI Wiki",
    "category": "Figma",
    "description": "Ready-to-use Figma designs and interface components.",
    "bestFor": "Use this resource for ready-to-use Figma designs and interface components.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, website"
  },
  {
    "id": 46,
    "name": "Vectorize Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "Vectorize Figma Plugin",
    "category": "Figma",
    "description": "Figma plugin for tracing raster images and converting them into editable vectors.",
    "bestFor": "Use this resource for figma plugin for tracing raster images and converting them into editable vectors.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 47,
    "name": "WebP Exporter Figma Plugin",
    "type": "Tool",
    "url": null,
    "platform": "WebP Exporter Figma Plugin",
    "category": "Figma",
    "description": "Figma exporter for producing lightweight WebP images for better website performance.",
    "bestFor": "Use this resource for figma exporter for producing lightweight WebP images for better website performance.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "figma, design resource, tool"
  },
  {
    "id": 48,
    "name": "App Shots",
    "type": "Website",
    "url": null,
    "platform": "App Shots",
    "category": "Inspiration",
    "description": "Design-research resource for application interfaces and screens.",
    "bestFor": "Use this resource for design-research resource for application interfaces and screens.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 49,
    "name": "Awwwards",
    "type": "Website",
    "url": "https://www.awwwards.com/",
    "platform": "Awwwards",
    "category": "Inspiration",
    "description": "A website that recognizes and promotes the talent and effort of the best web designers, developers, and agencies in the world.",
    "bestFor": "Generating UI inspiration from award-winning, interactive, and high-end 3D websites.",
    "audience": "Beginner",
    "access": "Free",
    "keywords": "web design, inspiration, awards, ui/ux, interaction, 3d design, awwwards, design trends, web awards, creative inspiration"
  },
  {
    "id": 50,
    "name": "Bento Grids",
    "type": "Website",
    "url": null,
    "platform": "Bento Grids",
    "category": "Inspiration",
    "description": "Gallery of bento-grid layouts and interface inspiration.",
    "bestFor": "Use this resource for gallery of bento-grid layouts and interface inspiration.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 51,
    "name": "btw Landing Pages",
    "type": "Website",
    "url": null,
    "platform": "btw Landing Pages",
    "category": "Inspiration",
    "description": "Landing-page builder and collection for quick website creation.",
    "bestFor": "Use this resource for landing-page builder and collection for quick website creation.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 52,
    "name": "Cherryp",
    "type": "Website",
    "url": null,
    "platform": "Cherryp",
    "category": "Inspiration",
    "description": "Curated source of design inspiration.",
    "bestFor": "Use this resource for curated source of design inspiration.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 53,
    "name": "DesignMunk",
    "type": "Website",
    "url": null,
    "platform": "DesignMunk",
    "category": "Inspiration",
    "description": "Curated web and landing-page design inspiration.",
    "bestFor": "Use this resource for curated web and landing-page design inspiration.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 54,
    "name": "Dribbble",
    "type": "Inspiration",
    "url": null,
    "platform": "Dribbble",
    "category": "Inspiration",
    "description": "A social networking platform for digital designers and creatives.",
    "bestFor": "Showcasing portfolios and discovering trending designs.",
    "audience": "Designer",
    "access": "Freemium",
    "keywords": "inspiration, trends, ui, design, portfolio, social media"
  },
  {
    "id": 55,
    "name": "Footer Design",
    "type": "Website",
    "url": null,
    "platform": "Footer Design",
    "category": "Inspiration",
    "description": "Curated gallery dedicated to website footer designs.",
    "bestFor": "Use this resource for curated gallery dedicated to website footer designs.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 56,
    "name": "Framer Community Gallery",
    "type": "Website",
    "url": "https://www.framer.com/community/",
    "platform": "Framer",
    "category": "Inspiration",
    "description": "A showcase of high-quality websites built using Framer, serving as a design and animation reference.",
    "bestFor": "Generating UI inspiration and extracting editable layouts to use in design tools like Figma.",
    "audience": "Beginner",
    "access": "Free",
    "keywords": "framer, design inspiration, ui layouts, web design gallery"
  },
  {
    "id": 57,
    "name": "Framer Gallery",
    "type": "Web Page",
    "url": "https://www.framer.com/gallery/",
    "platform": "Framer",
    "category": "Inspiration",
    "description": "A curated collection of websites and landing pages built using the Framer website builder.",
    "bestFor": "Finding realistic design references for SaaS landing pages and corporate projects.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "framer, landing page, saas, web design, gallery, inspiration"
  },
  {
    "id": 58,
    "name": "Good Design Tools",
    "type": "Website",
    "url": null,
    "platform": "Good Design Tools",
    "category": "Inspiration",
    "description": "Directory of tools and resources for designers.",
    "bestFor": "Use this resource for directory of tools and resources for designers.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 59,
    "name": "Land Book",
    "type": "Website",
    "url": null,
    "platform": "Land Book",
    "category": "Inspiration",
    "description": "Curated gallery of landing pages and website designs.",
    "bestFor": "Use this resource for curated gallery of landing pages and website designs.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 60,
    "name": "Landing Love",
    "type": "Website",
    "url": null,
    "platform": "Landing Love",
    "category": "Inspiration",
    "description": "Gallery of animated and interactive landing-page inspiration.",
    "bestFor": "Use this resource for gallery of animated and interactive landing-page inspiration.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 61,
    "name": "LandingFolio",
    "type": "Website",
    "url": null,
    "platform": "LandingFolio",
    "category": "Inspiration",
    "description": "Curated landing-page examples and component inspiration.",
    "bestFor": "Use this resource for curated landing-page examples and component inspiration.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 62,
    "name": "Lapa Ninja",
    "type": "Inspiration",
    "url": null,
    "platform": "Lapa Ninja",
    "category": "Inspiration",
    "description": "A collection of landing page designs for inspiration.",
    "bestFor": "Exploring finished websites rather than just mockups.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "web design, inspiration, live sites, landing page"
  },
  {
    "id": 63,
    "name": "Layers",
    "type": "Website",
    "url": null,
    "platform": "Layers",
    "category": "Inspiration",
    "description": "Design community and inspiration platform.",
    "bestFor": "Use this resource for design community and inspiration platform.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 64,
    "name": "Mobbin",
    "type": "Website",
    "url": null,
    "platform": "Mobbin",
    "category": "Inspiration",
    "description": "A comprehensive library of mobile and web design screenshots.",
    "bestFor": "Researching mobile UI patterns and user flows.",
    "audience": "Designer",
    "access": "Freemium",
    "keywords": "ui, mobile, design patterns, inspiration"
  },
  {
    "id": 65,
    "name": "Muzli",
    "type": "Website",
    "url": null,
    "platform": "Muzli",
    "category": "Inspiration",
    "description": "Design inspiration feed and creative-industry discovery platform.",
    "bestFor": "Use this resource for design inspiration feed and creative-industry discovery platform.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 66,
    "name": "One Page Love",
    "type": "Website",
    "url": null,
    "platform": "One Page Love",
    "category": "Inspiration",
    "description": "Gallery of one-page websites and landing pages.",
    "bestFor": "Use this resource for gallery of one-page websites and landing pages.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 67,
    "name": "Pafolios",
    "type": "Website",
    "url": null,
    "platform": "Pafolios",
    "category": "Inspiration",
    "description": "Portfolio design inspiration and examples.",
    "bestFor": "Use this resource for portfolio design inspiration and examples.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 68,
    "name": "Page Flows",
    "type": "Website",
    "url": null,
    "platform": "Page Flows",
    "category": "Inspiration",
    "description": "Library of real user flows and interface recordings.",
    "bestFor": "Use this resource for library of real user flows and interface recordings.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 69,
    "name": "Pinterest",
    "type": "Website",
    "url": "https://www.pinterest.com/",
    "platform": "Pinterest",
    "category": "Inspiration",
    "description": "A visual discovery engine for finding ideas like design references, photography, and layouts.",
    "bestFor": "Searching for initial visual identity and static design inspiration.",
    "audience": "Beginner",
    "access": "Free",
    "keywords": "design, mood board, branding, visual reference, pinterest, design reference, visual search"
  },
  {
    "id": 70,
    "name": "Really Good Emails",
    "type": "Website",
    "url": null,
    "platform": "Really Good Emails",
    "category": "Inspiration",
    "description": "A gallery showcasing best-in-class email designs.",
    "bestFor": "Finding inspiration for email marketing campaigns.",
    "audience": "Marketer",
    "access": "Free",
    "keywords": "email, marketing, inspiration, design"
  },
  {
    "id": 71,
    "name": "Refero Design",
    "type": "Website",
    "url": null,
    "platform": "Refero Design",
    "category": "Inspiration",
    "description": "Design research companion with real product-interface references.",
    "bestFor": "Use this resource for design research companion with real product-interface references.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 72,
    "name": "SaaS Landing Page",
    "type": "Website",
    "url": null,
    "platform": "SaaS Landing Page",
    "category": "Inspiration",
    "description": "Collection of SaaS landing-page examples.",
    "bestFor": "Use this resource for collection of SaaS landing-page examples.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 73,
    "name": "Savee",
    "type": "Website",
    "url": null,
    "platform": "Savee",
    "category": "Inspiration",
    "description": "Visual bookmarking and design-inspiration platform.",
    "bestFor": "Use this resource for visual bookmarking and design-inspiration platform.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 74,
    "name": "Screenshots Club",
    "type": "Website",
    "url": null,
    "platform": "Screenshots Club",
    "category": "Inspiration",
    "description": "Curated collection of digital-design screenshots and references.",
    "bestFor": "Use this resource for curated collection of digital-design screenshots and references.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 75,
    "name": "Super Hero",
    "type": "Website",
    "url": null,
    "platform": "Super Hero",
    "category": "Inspiration",
    "description": "Website hero-section inspiration library.",
    "bestFor": "Use this resource for website hero-section inspiration library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 76,
    "name": "User Onboarding",
    "type": "Website",
    "url": null,
    "platform": "User Onboarding",
    "category": "Inspiration",
    "description": "Collection of onboarding flows and product experience examples.",
    "bestFor": "Use this resource for collection of onboarding flows and product experience examples.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "inspiration, design resource, website"
  },
  {
    "id": 77,
    "name": "Pexels",
    "type": "Website",
    "url": "https://www.pexels.com/",
    "platform": "Pexels",
    "category": "Photography",
    "description": "Free stock-photo and video library for creative projects.",
    "bestFor": "Use this resource for free stock-photo and video library for creative projects.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "photography, design resource, website"
  },
  {
    "id": 78,
    "name": "Pixabay",
    "type": "Website",
    "url": "https://pixabay.com/",
    "platform": "Pixabay",
    "category": "Photography",
    "description": "Library of royalty-free photos, illustrations, videos, and creative media.",
    "bestFor": "Use this resource for library of royalty-free photos, illustrations, videos, and creative media.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "photography, design resource, website"
  },
  {
    "id": 79,
    "name": "Unsplash",
    "type": "Website",
    "url": null,
    "platform": "Unsplash",
    "category": "Photography",
    "description": "High-quality free photos that do not look like traditional stock photography.",
    "bestFor": "Finding high-resolution imagery for web projects.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "photography, stock, free, images"
  },
  {
    "id": 80,
    "name": "Notion",
    "type": "Tool",
    "url": null,
    "platform": "Notion",
    "category": "Productivity",
    "description": "An all-in-one workspace for notes, tasks, and wikis.",
    "bestFor": "Managing design projects and documentation.",
    "audience": "Business Owner",
    "access": "Freemium",
    "keywords": "productivity, notes, workspace, management"
  },
  {
    "id": 81,
    "name": "OBS Studio",
    "type": "Tool",
    "url": "https://obsproject.com/",
    "platform": "OBS Project",
    "category": "Productivity",
    "description": "Free and open-source software for video recording and live streaming.",
    "bestFor": "Recording screen interactions of websites to provide as visual context for AI prompts.",
    "audience": "Intermediate",
    "access": "Free",
    "keywords": "screen recording, obs, video capture, ai context"
  },
  {
    "id": 82,
    "name": "Absurd Design",
    "type": "Website",
    "url": null,
    "platform": "Absurd Design",
    "category": "Resources",
    "description": "Hand-drawn illustration collection with an unconventional visual style.",
    "bestFor": "Use this resource for hand-drawn illustration collection with an unconventional visual style.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 83,
    "name": "Adobe Fonts",
    "type": "Website",
    "url": null,
    "platform": "Adobe Fonts",
    "category": "Resources",
    "description": "Font library included with Adobe Creative Cloud.",
    "bestFor": "Use this resource for font library included with Adobe Creative Cloud.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 84,
    "name": "Animated Emojis",
    "type": "Website",
    "url": null,
    "platform": "Animated Emojis",
    "category": "Resources",
    "description": "Collection of animated emoji assets for digital projects.",
    "bestFor": "Use this resource for collection of animated emoji assets for digital projects.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 85,
    "name": "Avataaars",
    "type": "Tool",
    "url": null,
    "platform": "Avataaars",
    "category": "Resources",
    "description": "Avatar illustration generator and character library.",
    "bestFor": "Use this resource for avatar illustration generator and character library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 86,
    "name": "CapCut",
    "type": "Tool",
    "url": null,
    "platform": "CapCut",
    "category": "Resources",
    "description": "Video-editing platform for social, marketing, and creative content.",
    "bestFor": "Use this resource for video-editing platform for social, marketing, and creative content.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 87,
    "name": "Comunidade Skills",
    "type": "Website",
    "url": "https://www.comunidadeskills.com/",
    "platform": "Comunidade Skills",
    "category": "Resources",
    "description": "Resource hub for Figma, Framer, AI, design tools, and creative references.",
    "bestFor": "Use this resource for resource hub for Figma, Framer, AI, design tools, and creative references.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 88,
    "name": "Daily UI",
    "type": "Website",
    "url": null,
    "platform": "Daily UI",
    "category": "Resources",
    "description": "Daily interface-design prompts for building UI practice.",
    "bestFor": "Use this resource for daily interface-design prompts for building UI practice.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 89,
    "name": "Design Systems Brasileiros",
    "type": "Website",
    "url": null,
    "platform": "Design Systems Brasileiros",
    "category": "Resources",
    "description": "Collection of Brazilian design systems and references.",
    "bestFor": "Use this resource for collection of Brazilian design systems and references.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 90,
    "name": "Design Systems for Figma",
    "type": "Website",
    "url": null,
    "platform": "Design Systems for Figma",
    "category": "Resources",
    "description": "Reference collection for Figma-ready design-system resources.",
    "bestFor": "Use this resource for reference collection for Figma-ready design-system resources.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 91,
    "name": "Designercize",
    "type": "Tool",
    "url": null,
    "platform": "Designercize",
    "category": "Resources",
    "description": "Generates randomized design challenges with constraints.",
    "bestFor": "Use this resource for generates randomized design challenges with constraints.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 92,
    "name": "DrawKit",
    "type": "Website",
    "url": null,
    "platform": "DrawKit",
    "category": "Resources",
    "description": "Free and premium illustrations for websites and applications.",
    "bestFor": "Use this resource for free and premium illustrations for websites and applications.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 93,
    "name": "Epidemic Sound",
    "type": "Website",
    "url": null,
    "platform": "Epidemic Sound",
    "category": "Resources",
    "description": "Licensed music and sound-effects library for video and content production.",
    "bestFor": "Use this resource for licensed music and sound-effects library for video and content production.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 94,
    "name": "Eva Icons",
    "type": "Website",
    "url": null,
    "platform": "Eva Icons",
    "category": "Resources",
    "description": "Open-source icon library for interface design.",
    "bestFor": "Use this resource for open-source icon library for interface design.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 95,
    "name": "FakeClients",
    "type": "Tool",
    "url": null,
    "platform": "FakeClients",
    "category": "Resources",
    "description": "Generates fictional client briefs for creative practice.",
    "bestFor": "Use this resource for generates fictional client briefs for creative practice.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 96,
    "name": "Font Awesome",
    "type": "Website",
    "url": null,
    "platform": "Font Awesome",
    "category": "Resources",
    "description": "Popular open-source icon toolkit providing vector icons and social logos.",
    "bestFor": "Use this resource for popular open-source icon toolkit providing vector icons and social logos.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 97,
    "name": "FontPair",
    "type": "Website",
    "url": null,
    "platform": "FontPair",
    "category": "Resources",
    "description": "Typography resource for discovering complementary font pairings.",
    "bestFor": "Use this resource for typography resource for discovering complementary font pairings.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 98,
    "name": "Fontshare",
    "type": "Website",
    "url": null,
    "platform": "Fontshare",
    "category": "Resources",
    "description": "Free font service and typeface library.",
    "bestFor": "Use this resource for free font service and typeface library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 99,
    "name": "Free Illustrations",
    "type": "Website",
    "url": null,
    "platform": "Free Illustrations",
    "category": "Resources",
    "description": "Collection of free illustration resources for design projects.",
    "bestFor": "Use this resource for collection of free illustration resources for design projects.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 100,
    "name": "Goodbrief",
    "type": "Tool",
    "url": null,
    "platform": "Goodbrief",
    "category": "Resources",
    "description": "Generates creative briefs for design practice and concept development.",
    "bestFor": "Use this resource for generates creative briefs for design practice and concept development.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 101,
    "name": "Growth.Design",
    "type": "Website",
    "url": null,
    "platform": "Growth.Design",
    "category": "Resources",
    "description": "Product psychology case studies presented as visual learning experiences.",
    "bestFor": "Use this resource for product psychology case studies presented as visual learning experiences.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 102,
    "name": "Halo UI/UX",
    "type": "Website",
    "url": null,
    "platform": "Halo UI/UX",
    "category": "Resources",
    "description": "UI and UX resource collection shown in the resource bank.",
    "bestFor": "Use this resource for uI and UX resource collection shown in the resource bank.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 103,
    "name": "Handz",
    "type": "Website",
    "url": null,
    "platform": "Handz",
    "category": "Resources",
    "description": "3D hand-gesture illustration library.",
    "bestFor": "Use this resource for 3D hand-gesture illustration library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 104,
    "name": "Humaaans",
    "type": "Website",
    "url": null,
    "platform": "Humaaans",
    "category": "Resources",
    "description": "Mix-and-match illustration library of people and scenes.",
    "bestFor": "Use this resource for mix-and-match illustration library of people and scenes.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 105,
    "name": "Icon Hunt",
    "type": "Website",
    "url": null,
    "platform": "Icon Hunt",
    "category": "Resources",
    "description": "Search and discovery resource for icon collections.",
    "bestFor": "Use this resource for search and discovery resource for icon collections.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 106,
    "name": "Iconoir",
    "type": "Website",
    "url": null,
    "platform": "Iconoir",
    "category": "Resources",
    "description": "Open-source icon library with consistent outline styling.",
    "bestFor": "Use this resource for open-source icon library with consistent outline styling.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 107,
    "name": "IconPark",
    "type": "Website",
    "url": null,
    "platform": "IconPark",
    "category": "Resources",
    "description": "Large customizable open-source icon library.",
    "bestFor": "Use this resource for large customizable open-source icon library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 108,
    "name": "Icons8",
    "type": "Website",
    "url": null,
    "platform": "Icons8",
    "category": "Resources",
    "description": "Library of icons, illustrations, photos, music, and design assets.",
    "bestFor": "Use this resource for library of icons, illustrations, photos, music, and design assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 109,
    "name": "IRA Design",
    "type": "Website",
    "url": null,
    "platform": "IRA Design",
    "category": "Resources",
    "description": "Customizable illustration library for digital products.",
    "bestFor": "Use this resource for customizable illustration library for digital products.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 110,
    "name": "Justinmind Wireframing Guide",
    "type": "Web Page",
    "url": "https://www.justinmind.com/wireframe/low-fidelity-vs-high-fidelity-wireframing-is-paper-dead",
    "platform": "Justinmind Wireframing Guide",
    "category": "Resources",
    "description": "Guide comparing low-fidelity and high-fidelity wireframing methods.",
    "bestFor": "Use this resource for guide comparing low-fidelity and high-fidelity wireframing methods.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, web page"
  },
  {
    "id": 111,
    "name": "Khroma",
    "type": "Tool",
    "url": null,
    "platform": "Khroma",
    "category": "Resources",
    "description": "AI-assisted color palette discovery and generation tool.",
    "bestFor": "Use this resource for aI-assisted color palette discovery and generation tool.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 112,
    "name": "LS Graphics",
    "type": "Website",
    "url": null,
    "platform": "LS Graphics",
    "category": "Resources",
    "description": "Creative mockup and design-asset library.",
    "bestFor": "Use this resource for creative mockup and design-asset library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 113,
    "name": "Mesh Gradients",
    "type": "Tool",
    "url": null,
    "platform": "Mesh Gradients",
    "category": "Resources",
    "description": "Creates and provides colorful mesh-gradient assets.",
    "bestFor": "Use this resource for creates and provides colorful mesh-gradient assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 114,
    "name": "NHS Design System",
    "type": "Website",
    "url": null,
    "platform": "NHS Design System",
    "category": "Resources",
    "description": "Public design-system guidance, patterns, and interface standards.",
    "bestFor": "Use this resource for public design-system guidance, patterns, and interface standards.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 115,
    "name": "Noise & Gradient",
    "type": "Tool",
    "url": null,
    "platform": "Noise & Gradient",
    "category": "Resources",
    "description": "Generates gradient backgrounds with configurable noise and texture.",
    "bestFor": "Use this resource for generates gradient backgrounds with configurable noise and texture.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 116,
    "name": "Open Doodles",
    "type": "Website",
    "url": null,
    "platform": "Open Doodles",
    "category": "Resources",
    "description": "Free hand-drawn illustration library.",
    "bestFor": "Use this resource for free hand-drawn illustration library.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 117,
    "name": "Realtime Colors",
    "type": "Tool",
    "url": null,
    "platform": "Realtime Colors",
    "category": "Resources",
    "description": "Previews color palettes on a real interface before implementation.",
    "bestFor": "Use this resource for previews color palettes on a real interface before implementation.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 118,
    "name": "ShapeFest",
    "type": "Website",
    "url": null,
    "platform": "ShapeFest",
    "category": "Resources",
    "description": "Large collection of free 3D shapes and illustrations.",
    "bestFor": "Use this resource for large collection of free 3D shapes and illustrations.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 119,
    "name": "Sharpen",
    "type": "Tool",
    "url": null,
    "platform": "Sharpen",
    "category": "Resources",
    "description": "Generates design challenges and creative prompts.",
    "bestFor": "Use this resource for generates design challenges and creative prompts.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 120,
    "name": "Storyset",
    "type": "Website",
    "url": null,
    "platform": "Storyset",
    "category": "Resources",
    "description": "Customizable illustration collections for digital storytelling.",
    "bestFor": "Use this resource for customizable illustration collections for digital storytelling.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 121,
    "name": "The Design System Checklist",
    "type": "Website",
    "url": null,
    "platform": "The Design System Checklist",
    "category": "Resources",
    "description": "Checklist for planning and validating a complete design system.",
    "bestFor": "Use this resource for checklist for planning and validating a complete design system.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 122,
    "name": "Toolfolio",
    "type": "Website",
    "url": null,
    "platform": "Toolfolio",
    "category": "Resources",
    "description": "A curated collection of resources, tools, and products for designers.",
    "bestFor": "Finding curated design tools and products.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "tools, curated, design resources"
  },
  {
    "id": 123,
    "name": "Type Scale",
    "type": "Tool",
    "url": null,
    "platform": "Type Scale",
    "category": "Resources",
    "description": "Creates harmonious typographic scales for interface design.",
    "bestFor": "Use this resource for creates harmonious typographic scales for interface design.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 124,
    "name": "Typewolf",
    "type": "Website",
    "url": null,
    "platform": "Typewolf",
    "category": "Resources",
    "description": "Typography inspiration and font recommendations based on real websites.",
    "bestFor": "Use this resource for typography inspiration and font recommendations based on real websites.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 125,
    "name": "UI Goodies",
    "type": "Website",
    "url": null,
    "platform": "UI Goodies",
    "category": "Resources",
    "description": "Curated directory of UI design resources and tools.",
    "bestFor": "Use this resource for curated directory of UI design resources and tools.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 126,
    "name": "UI8",
    "type": "Website",
    "url": null,
    "platform": "UI8",
    "category": "Resources",
    "description": "Marketplace for UI kits, fonts, icons, and creative assets.",
    "bestFor": "Use this resource for marketplace for UI kits, fonts, icons, and creative assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 127,
    "name": "UX Challenges",
    "type": "Website",
    "url": null,
    "platform": "UX Challenges",
    "category": "Resources",
    "description": "UX exercises and prompts for practicing product-design skills.",
    "bestFor": "Use this resource for uX exercises and prompts for practicing product-design skills.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, website"
  },
  {
    "id": 128,
    "name": "WhatFontIs",
    "type": "Tool",
    "url": null,
    "platform": "WhatFontIs",
    "category": "Resources",
    "description": "Identifies fonts from uploaded images.",
    "bestFor": "Use this resource for identifies fonts from uploaded images.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "resources, design resource, tool"
  },
  {
    "id": 129,
    "name": "Google Fonts",
    "type": "Website",
    "url": null,
    "platform": "Google",
    "category": "Typography",
    "description": "A library of free and open-source font families.",
    "bestFor": "Selecting and implementing web fonts.",
    "audience": "Designer",
    "access": "Free",
    "keywords": "typography, fonts, google, web design"
  },
  {
    "id": 130,
    "name": "WhatFont",
    "type": "Tool",
    "url": null,
    "platform": "WhatFont",
    "category": "Typography",
    "description": "Browser extension for identifying fonts used on webpages.",
    "bestFor": "Use this resource for browser extension for identifying fonts used on webpages.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "typography, design resource, tool"
  },
  {
    "id": 131,
    "name": "Wix Web Safe Fonts Guide",
    "type": "Web Page",
    "url": "https://www.wix.com/blog/web-safe-fonts",
    "platform": "Wix Web Safe Fonts Guide",
    "category": "Typography",
    "description": "Guide to web-safe fonts and reliable typography choices for websites.",
    "bestFor": "Use this resource for guide to web-safe fonts and reliable typography choices for websites.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "typography, design resource, web page"
  },
  {
    "id": 132,
    "name": "Blobmaker",
    "type": "Tool",
    "url": "https://www.blobmaker.app/",
    "platform": "Blobmaker",
    "category": "Web Development",
    "description": "Generator for creating customizable organic SVG blob shapes.",
    "bestFor": "Use this resource for generator for creating customizable organic SVG blob shapes.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 133,
    "name": "Boosters",
    "type": "Tool",
    "url": null,
    "platform": "Boosters",
    "category": "Web Development",
    "description": "Advanced code solutions that integrate directly into Webflow.",
    "bestFor": "Adding advanced functionality to Webflow sites.",
    "audience": "Developer",
    "access": "Free",
    "keywords": "webflow, code, customization, development"
  },
  {
    "id": 134,
    "name": "Brumm Shadow Generator",
    "type": "Tool",
    "url": "https://shadows.brumm.af/",
    "platform": "Brumm Shadow Generator",
    "category": "Web Development",
    "description": "Web tool for creating and tuning layered CSS box shadows.",
    "bestFor": "Use this resource for web tool for creating and tuning layered CSS box shadows.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 135,
    "name": "CSS Packer",
    "type": "Tool",
    "url": null,
    "platform": "CSS Packer",
    "category": "Web Development",
    "description": "Browser utility referenced for compressing or packing CSS.",
    "bestFor": "Use this resource for browser utility referenced for compressing or packing CSS.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 136,
    "name": "Export SVG Extension",
    "type": "Tool",
    "url": null,
    "platform": "Export SVG Extension",
    "category": "Web Development",
    "description": "Browser extension referenced for exporting SVG assets from webpages.",
    "bestFor": "Use this resource for browser extension referenced for exporting SVG assets from webpages.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 137,
    "name": "Flowbase",
    "type": "Website",
    "url": null,
    "platform": "Flowbase",
    "category": "Web Development",
    "description": "A library of cloneable assets and templates for Webflow.",
    "bestFor": "Speeding up Webflow development with pre-built components.",
    "audience": "Developer",
    "access": "Freemium",
    "keywords": "webflow, cloneable, templates, assets"
  },
  {
    "id": 138,
    "name": "Framer",
    "type": "Tool",
    "url": null,
    "platform": "Framer",
    "category": "Web Development",
    "description": "Visual website builder referenced for moving Figma designs into interactive HTML websites.",
    "bestFor": "Use this resource for visual website builder referenced for moving Figma designs into interactive HTML websites.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 139,
    "name": "Get Waves",
    "type": "Tool",
    "url": "https://getwaves.io/",
    "platform": "Get Waves",
    "category": "Web Development",
    "description": "Generator for creating customizable SVG wave shapes for websites.",
    "bestFor": "Use this resource for generator for creating customizable SVG wave shapes for websites.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 140,
    "name": "Google reCAPTCHA",
    "type": "Tool",
    "url": null,
    "platform": "Google reCAPTCHA",
    "category": "Web Development",
    "description": "Google anti-abuse service used to protect website forms from spam and automated submissions.",
    "bestFor": "Use this resource for google anti-abuse service used to protect website forms from spam and automated submissions.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 141,
    "name": "GSAP (GreenSock Animation Platform)",
    "type": "Tool",
    "url": "https://gsap.com/",
    "platform": "GreenSock",
    "category": "Web Development",
    "description": "A robust JavaScript library for creating high-performance, professional web animations.",
    "bestFor": "Creating interactive scroll animations, vector drawings, and complex UI motion.",
    "audience": "Beginner",
    "access": "Freemium",
    "keywords": "javascript, animation, gsap, scrolltrigger, frontend"
  },
  {
    "id": 142,
    "name": "Haikei",
    "type": "Tool",
    "url": "https://app.haikei.app/",
    "platform": "Haikei",
    "category": "Web Development",
    "description": "Generator for SVG backgrounds, waves, blobs, gradients, and abstract visual assets.",
    "bestFor": "Use this resource for generator for SVG backgrounds, waves, blobs, gradients, and abstract visual assets.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 143,
    "name": "Hero Patterns",
    "type": "Website",
    "url": "https://heropatterns.com/",
    "platform": "Hero Patterns",
    "category": "Web Development",
    "description": "Collection of repeatable SVG background patterns for websites.",
    "bestFor": "Use this resource for collection of repeatable SVG background patterns for websites.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, website"
  },
  {
    "id": 144,
    "name": "Image-to-ThreeJS",
    "type": "Tool",
    "url": null,
    "platform": "GitHub (Image 2 3JS Repository)",
    "category": "Web Development",
    "description": "A repository that allows users to convert 2D images into interactive 3D objects using Three.js code.",
    "bestFor": "Generating 3D web elements from simple image prompts with the help of AI.",
    "audience": "Beginner",
    "access": "Free",
    "keywords": "threejs, 3d, ai, javascript, image to 3d"
  },
  {
    "id": 145,
    "name": "Meyerweb CSS Reset",
    "type": "Web Page",
    "url": "https://meyerweb.com/eric/tools/css/reset/",
    "platform": "Meyerweb CSS Reset",
    "category": "Web Development",
    "description": "Classic CSS reset stylesheet for reducing browser-default styling inconsistencies.",
    "bestFor": "Use this resource for classic CSS reset stylesheet for reducing browser-default styling inconsistencies.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "web development, design resource, web page"
  },
  {
    "id": 146,
    "name": "Neumorphism.io",
    "type": "Tool",
    "url": "https://neumorphism.io/#e0e0e0",
    "platform": "Neumorphism.io",
    "category": "Web Development",
    "description": "CSS generator for experimenting with neumorphic interface styles.",
    "bestFor": "Use this resource for cSS generator for experimenting with neumorphic interface styles.",
    "audience": "Designer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 147,
    "name": "React Bits",
    "type": "Website",
    "url": "https://react-bits.com/",
    "platform": "React Bits",
    "category": "Web Development",
    "description": "An open-source library of animated and interactive React components including backgrounds and text effects.",
    "bestFor": "Enhancing web projects with advanced background effects, shaders, and animated UI components.",
    "audience": "Beginner",
    "access": "Freemium",
    "keywords": "react, components, shaders, animations, frontend, animation, ui library, interactive backgrounds"
  },
  {
    "id": 148,
    "name": "TweakCN",
    "type": "Tool",
    "url": null,
    "platform": "TweakCN",
    "category": "Web Development",
    "description": "Advanced web interface customization tool referenced for development workflows.",
    "bestFor": "Use this resource for advanced web interface customization tool referenced for development workflows.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 149,
    "name": "Uiverse",
    "type": "Website",
    "url": "https://uiverse.io/",
    "platform": "Uiverse",
    "category": "Web Development",
    "description": "A library of free, open-source UI elements made with CSS or Tailwind, featuring interactive buttons, loaders, and cards.",
    "bestFor": "Providing a code base for AI to customize or for quickly adding interactive UI components to a web project.",
    "audience": "Beginner",
    "access": "Free",
    "keywords": "ui elements, css, buttons, loaders, web design, frontend"
  },
  {
    "id": 150,
    "name": "Vite",
    "type": "Tool",
    "url": null,
    "platform": "Vite",
    "category": "Web Development",
    "description": "A build tool that provides a fast development environment for modern web projects.",
    "bestFor": "Running and previewing React projects locally.",
    "audience": "Developer",
    "access": "Free",
    "keywords": "vite, development server, react, frontend tool"
  },
  {
    "id": 151,
    "name": "Wappalyzer",
    "type": "Tool",
    "url": null,
    "platform": "Wappalyzer",
    "category": "Web Development",
    "description": "Technology profiler that identifies frameworks, services, and platforms used by websites.",
    "bestFor": "Use this resource for technology profiler that identifies frameworks, services, and platforms used by websites.",
    "audience": "Developer",
    "access": "Unknown",
    "keywords": "web development, design resource, tool"
  },
  {
    "id": 152,
    "name": "Webflow",
    "type": "Tool",
    "url": null,
    "platform": "Webflow",
    "category": "Web Development",
    "description": "A professional web design tool and hosting platform.",
    "bestFor": "Building and hosting production-ready websites without writing code.",
    "audience": "Developer",
    "access": "Subscription",
    "keywords": "web design, cms, development, no-code"
  }
];

