import type { Resource } from "./resources";

export const uiLibraries: Resource[] = [
  {
    id: 301,
    name: "Radix UI",
    type: "Library",
    url: "https://www.radix-ui.com/",
    platform: "WorkOS",
    category: "UI Component Libraries",
    description: "Accessible, unstyled React primitives for building custom design systems and interface components.",
    bestFor: "Building highly customized interfaces from robust accessible primitives.",
    audience: "Developer",
    access: "Free",
    keywords: "react, primitives, accessible, headless, design system, ui library"
  },
  {
    id: 302,
    name: "Ark UI",
    type: "Library",
    url: "https://ark-ui.com/",
    platform: "Chakra Systems",
    category: "UI Component Libraries",
    description: "Headless component library for building reusable design systems across modern JavaScript frameworks.",
    bestFor: "Creating accessible custom component systems without adopting preset visual styles.",
    audience: "Developer",
    access: "Free",
    keywords: "headless ui, react, vue, solid, accessible, primitives"
  },
  {
    id: 303,
    name: "Park UI",
    type: "Library",
    url: "https://park-ui.com/",
    platform: "Park UI",
    category: "UI Component Libraries",
    description: "Open-code component system built with Ark UI and Panda CSS, designed for customization and design-system ownership.",
    bestFor: "Using a shadcn-like open-code workflow with Ark UI and Panda CSS.",
    audience: "Developer",
    access: "Free",
    keywords: "open code, ark ui, panda css, react, solid, design system"
  },
  {
    id: 304,
    name: "Mantine",
    type: "Library",
    url: "https://mantine.dev/",
    platform: "Mantine",
    category: "UI Component Libraries",
    description: "Feature-rich React component and hooks library for building applications, dashboards, forms, and product interfaces.",
    bestFor: "Shipping full React applications quickly with a broad component and hooks ecosystem.",
    audience: "Developer",
    access: "Free",
    keywords: "react, components, hooks, forms, dashboard, ui library"
  },
  {
    id: 305,
    name: "Chakra UI",
    type: "Library",
    url: "https://chakra-ui.com/",
    platform: "Chakra Systems",
    category: "UI Component Libraries",
    description: "Accessible React component system for building products and custom design systems with composable styling APIs.",
    bestFor: "Building accessible React products with a mature styling and theming system.",
    audience: "Developer",
    access: "Free",
    keywords: "react, accessible, components, design system, chakra"
  },
  {
    id: 306,
    name: "HeroUI",
    type: "Library",
    url: "https://heroui.com/",
    platform: "HeroUI",
    category: "UI Component Libraries",
    description: "Modern React and React Native UI library with accessible behavior, Tailwind styling, typed APIs, and polished defaults.",
    bestFor: "Building polished modern interfaces with strong defaults and accessible interactions.",
    audience: "Developer",
    access: "Free",
    keywords: "react, tailwind, react aria, components, nextui, heroui"
  },
  {
    id: 307,
    name: "daisyUI",
    type: "Library",
    url: "https://daisyui.com/",
    platform: "daisyUI",
    category: "UI Component Libraries",
    description: "Tailwind CSS component plugin with semantic class names, themes, and a large collection of common interface patterns.",
    bestFor: "Rapidly building Tailwind interfaces with minimal component boilerplate.",
    audience: "Developer",
    access: "Freemium",
    keywords: "tailwind, css, components, themes, semantic classes"
  },
  {
    id: 308,
    name: "Flowbite",
    type: "Library",
    url: "https://flowbite.com/",
    platform: "Flowbite",
    category: "UI Component Libraries",
    description: "Tailwind CSS component ecosystem with interactive UI patterns, application components, templates, and framework integrations.",
    bestFor: "Building practical Tailwind applications from a large catalog of ready-made patterns.",
    audience: "Developer",
    access: "Freemium",
    keywords: "tailwind, components, templates, react, vue, ui library"
  },
  {
    id: 309,
    name: "Preline UI",
    type: "Library",
    url: "https://preline.co/",
    platform: "Preline",
    category: "UI Component Libraries",
    description: "Open-source Tailwind CSS component library with application patterns, overlays, navigation, forms, and layout examples.",
    bestFor: "Adding production-oriented Tailwind components and interactive patterns quickly.",
    audience: "Developer",
    access: "Freemium",
    keywords: "tailwind, components, html, javascript, ui library"
  },
  {
    id: 310,
    name: "Headless UI",
    type: "Library",
    url: "https://headlessui.com/",
    platform: "Tailwind Labs",
    category: "UI Component Libraries",
    description: "Completely unstyled, accessible UI components designed to integrate with Tailwind CSS and custom visual systems.",
    bestFor: "Owning the visual design while relying on accessible interaction behavior.",
    audience: "Developer",
    access: "Free",
    keywords: "headless, accessible, react, vue, tailwind, primitives"
  },
  {
    id: 311,
    name: "Material UI",
    type: "Library",
    url: "https://mui.com/material-ui/",
    platform: "MUI",
    category: "UI Component Libraries",
    description: "Comprehensive production-ready React component library implementing Material Design with extensive customization options.",
    bestFor: "Building robust product interfaces and dashboards with a mature component ecosystem.",
    audience: "Developer",
    access: "Freemium",
    keywords: "mui, material design, react, components, dashboard"
  },
  {
    id: 312,
    name: "Ant Design",
    type: "Library",
    url: "https://ant.design/",
    platform: "Ant Group",
    category: "UI Component Libraries",
    description: "Enterprise-focused React design system and component library with extensive data-entry, navigation, and feedback patterns.",
    bestFor: "Building complex dashboards, internal tools, and enterprise applications.",
    audience: "Developer",
    access: "Free",
    keywords: "react, enterprise, design system, components, dashboard"
  },
  {
    id: 313,
    name: "PrimeReact",
    type: "Library",
    url: "https://primereact.dev/",
    platform: "PrimeTek",
    category: "UI Component Libraries",
    description: "Large React component suite with data tables, trees, charts, pickers, overlays, forms, and enterprise widgets.",
    bestFor: "Building data-heavy applications that require advanced ready-made widgets.",
    audience: "Developer",
    access: "Freemium",
    keywords: "react, data table, enterprise, components, widgets"
  },
  {
    id: 314,
    name: "Tremor",
    type: "Library",
    url: "https://www.tremor.so/",
    platform: "Tremor",
    category: "UI Component Libraries",
    description: "React component library focused on dashboards, charts, analytics, and data-rich application interfaces.",
    bestFor: "Building analytics dashboards and polished data visualization interfaces.",
    audience: "Developer",
    access: "Free",
    keywords: "react, dashboard, charts, analytics, data visualization"
  },
  {
    id: 315,
    name: "Base UI",
    type: "Library",
    url: "https://base-ui.com/",
    platform: "MUI",
    category: "UI Component Libraries",
    description: "Unstyled React component library focused on accessible behavior and flexible composition for custom design systems.",
    bestFor: "Creating custom React design systems from low-level accessible primitives.",
    audience: "Developer",
    access: "Free",
    keywords: "headless, primitives, react, accessible, base ui"
  },
  {
    id: 316,
    name: "Kibo UI",
    type: "Library",
    url: "https://www.kibo-ui.com/",
    platform: "Kibo UI",
    category: "UI Component Libraries",
    description: "Open-source registry of composable, accessible components designed as an extension to shadcn/ui.",
    bestFor: "Adding richer functional components to an existing shadcn/ui project.",
    audience: "Developer",
    access: "Free",
    keywords: "shadcn, registry, react, tailwind, composable components"
  },
  {
    id: 317,
    name: "Dice UI",
    type: "Library",
    url: "https://diceui.com/",
    platform: "Dice UI",
    category: "UI Component Libraries",
    description: "Accessible, copy-paste-ready React and Tailwind components designed to complement shadcn/ui.",
    bestFor: "Expanding shadcn projects with composable interface components you own.",
    audience: "Developer",
    access: "Free",
    keywords: "shadcn, react, tailwind, copy paste, components"
  },
  {
    id: 318,
    name: "Cult UI",
    type: "Library",
    url: "https://www.cult-ui.com/",
    platform: "Cult UI",
    category: "UI Component Libraries",
    description: "Collection of modern React UI components and visual patterns intended for copy-paste customization.",
    bestFor: "Adding distinctive modern component patterns to React and shadcn-style projects.",
    audience: "Developer",
    access: "Free",
    keywords: "react, shadcn, components, copy paste, ui"
  },
  {
    id: 319,
    name: "Tailark",
    type: "Library",
    url: "https://tailark.com/",
    platform: "Tailark",
    category: "UI Component Libraries",
    description: "Tailwind-oriented collection of polished website sections and interface blocks for modern landing pages.",
    bestFor: "Assembling polished marketing pages and landing-page sections quickly.",
    audience: "Developer",
    access: "Freemium",
    keywords: "tailwind, blocks, landing page, components, sections"
  },
  {
    id: 320,
    name: "Float UI",
    type: "Library",
    url: "https://floatui.com/",
    platform: "Float UI",
    category: "UI Component Libraries",
    description: "Collection of responsive Tailwind CSS components and templates for websites, applications, and marketing interfaces.",
    bestFor: "Building responsive Tailwind pages from reusable sections and components.",
    audience: "Developer",
    access: "Free",
    keywords: "tailwind, components, templates, responsive, ui"
  },
  {
    id: 321,
    name: "HyperUI",
    type: "Library",
    url: "https://www.hyperui.dev/",
    platform: "HyperUI",
    category: "UI Component Libraries",
    description: "Free collection of copy-paste Tailwind CSS components for marketing websites, ecommerce, and application interfaces.",
    bestFor: "Quickly adding straightforward Tailwind components without a package dependency.",
    audience: "Developer",
    access: "Free",
    keywords: "tailwind, copy paste, components, ecommerce, ui"
  },
  {
    id: 322,
    name: "Meraki UI",
    type: "Library",
    url: "https://merakiui.com/",
    platform: "Meraki UI Labs",
    category: "UI Component Libraries",
    description: "Responsive Tailwind CSS component collection with dark-mode and RTL-friendly interface patterns.",
    bestFor: "Building Tailwind interfaces that need reusable responsive components and RTL support.",
    audience: "Developer",
    access: "Free",
    keywords: "tailwind, rtl, dark mode, components, responsive"
  },
  {
    id: 323,
    name: "TailGrids",
    type: "Library",
    url: "https://tailgrids.com/",
    platform: "TailGrids",
    category: "UI Component Libraries",
    description: "Tailwind CSS UI library offering components, blocks, templates, and application interface patterns.",
    bestFor: "Building Tailwind marketing sites and application layouts from prebuilt sections.",
    audience: "Developer",
    access: "Freemium",
    keywords: "tailwind, components, blocks, templates, ui"
  },
  {
    id: 324,
    name: "FlyonUI",
    type: "Library",
    url: "https://flyonui.com/",
    platform: "FlyonUI",
    category: "UI Component Libraries",
    description: "Tailwind CSS component library combining semantic utility patterns with interactive JavaScript components.",
    bestFor: "Building Tailwind interfaces with ready-to-use interactive components and themes.",
    audience: "Developer",
    access: "Free",
    keywords: "tailwind, components, javascript, themes, ui library"
  },
  {
    id: 325,
    name: "Catalyst",
    type: "Library",
    url: "https://catalyst.tailwindui.com/",
    platform: "Tailwind Labs",
    category: "UI Component Libraries",
    description: "Professional React application UI patterns and components from Tailwind Plus for production product interfaces.",
    bestFor: "Building premium Tailwind application interfaces with professionally designed patterns.",
    audience: "Developer",
    access: "Paid",
    keywords: "tailwind plus, catalyst, react, application ui, components"
  }
];
